const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("voiceAPI", {
  runtime: { isPackaged: !process.defaultApp },
  copy: (text) => ipcRenderer.invoke("clipboard:write", text),
  paste: (text) => ipcRenderer.invoke("clipboard:paste", text),
  exportHistory: (entries) => ipcRenderer.invoke("history:export", entries),
  getState: () => ipcRenderer.invoke("state:get"),
  migrateLegacyState: (state) => ipcRenderer.invoke("state:migrate-legacy", state),
  writeState: (state) => ipcRenderer.invoke("state:write", state),
  transcribe: (audio, language, profile, device) => ipcRenderer.invoke("transcription:run", audio, language, profile, device),
  overlay: (state) => ipcRenderer.invoke("overlay:set-state", state),
  taskbar: (state) => ipcRenderer.invoke("taskbar:set-state", state),
  diagnostics: () => ipcRenderer.invoke("app:diagnostics"),
  clearModels: () => ipcRenderer.invoke("models:clear"),
  getCloseBehavior: () => ipcRenderer.invoke("app:get-close-behavior"),
  setCloseBehavior: (behavior) => ipcRenderer.invoke("app:set-close-behavior", behavior),
  getAutoStart: () => ipcRenderer.invoke("preferences:get-autostart"),
  setAutoStart: (enabled) => ipcRenderer.invoke("preferences:set-autostart", enabled),
  getShortcuts: () => ipcRenderer.invoke("preferences:get-shortcuts"),
  setShortcuts: (shortcuts) => ipcRenderer.invoke("preferences:set-shortcuts", shortcuts),
  getShortcutMode: () => ipcRenderer.invoke("preferences:get-shortcut-mode"),
  setShortcutMode: (mode) => ipcRenderer.invoke("preferences:set-shortcut-mode", mode),
  minimize: () => ipcRenderer.invoke("window:minimize"),
  hide: () => ipcRenderer.invoke("window:hide"),
  onShortcutToggle: (callback) => ipcRenderer.on("shortcut:toggle", callback),
  onShortcutPressed: (callback) => ipcRenderer.on("shortcut:pressed", callback),
  onShortcutReleased: (callback) => ipcRenderer.on("shortcut:released", callback),
  onReprocess: (callback) => ipcRenderer.on("shortcut:reprocess", callback),
  onShortcutError: (callback) => ipcRenderer.on("shortcut:error", callback),
  onModelProgress: (callback) => ipcRenderer.on("model:progress", (_event, progress) => callback(progress)),
  onNavigate: (callback) => ipcRenderer.on("app:navigate", (_event, panel) => callback(panel)),
  onPasteLast: (callback) => ipcRenderer.on("tray:paste-last", callback)
});
